[General]
useBreezeIconTheme=true
useSystemTitleBar=false
hideHeaderBarOnMouseHide=true
rememberWindowSize=true

[Video]
pauseOnMinimize=true

[Subtitles]
subFont=Sans Serif
subFontSize=20
subColor=#FFFF00
