# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ self, ... }:

{
  flake.nixosModules.a520MHardware = { config, lib, pkgs, modulesPath, ...}: {
    imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
    boot.initrd.kernelModules = [ ];
    boot.kernelModules = [ "kvm-amd" ];
    boot.extraModulePackages = [ ];

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/db03026c-a5fc-4c36-9b03-f3502dfbb0d3";
        fsType = "btrfs";
      };

    fileSystems."/home" =
      { device = "/dev/disk/by-uuid/db03026c-a5fc-4c36-9b03-f3502dfbb0d3";
        fsType = "btrfs";
        options = [ "subvol=home" ];
      };

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/D1C5-45BC";
        fsType = "vfat";
        options = [ "fmask=0077" "dmask=0077" ];
      };

    fileSystems."/mnt/data" =
      { device = "/dev/disk/by-uuid/b198a58f-18f7-4dd3-a67e-cc1409ef166b";
        fsType = "ext4";
      };

    fileSystems."/mnt/games" =
      { device = "/dev/disk/by-uuid/9a60d75d-3156-4acd-b9d7-8bdb4e7488ac";
        fsType = "ext4";
      };

    fileSystems."/nix" =
      { device = "/dev/disk/by-uuid/c98f2433-bf74-4af7-b835-d487af19d002";
        fsType = "ext4";
      };

    swapDevices = [ ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
